# Generated by Django 4.2.27 on 2026-01-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grading_method",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword Matching"),
                            ("ai_assisted", "AI Assisted"),
                        ],
                        default="keyword",
                        max_length=20,
                    ),
                ),
                ("performance_analysis", models.JSONField(blank=True, default=dict)),
                ("suggestions", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("detailed_scores", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "grading_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
