# Generated by Django 4.2.27 on 2026-01-01 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grading", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingresult",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_result",
                to="submissions.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="gradingresult",
            index=models.Index(
                fields=["submission", "grading_method"],
                name="grading_res_submiss_5a4822_idx",
            ),
        ),
    ]
