# Generated by Django 4.2.27 on 2026-01-01 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="exams.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="submissions.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student", "status"], name="submissions_student_b380bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["exam", "is_graded"], name="submissions_exam_id_985b03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["submitted_at"], name="submissions_submitt_9b96b8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("student", "exam")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["submission", "question"], name="answers_submiss_4fd023_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "question")},
        ),
    ]
