# Generated by Django 4.2.27 on 2026-01-01 01:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("total_marks", models.PositiveIntegerField(default=0)),
                ("passing_marks", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("essay", "Essay"),
                            ("short_answer", "Short Answer"),
                            ("paragraph", "Paragraph"),
                        ],
                        default="essay",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "expected_answer",
                    models.TextField(help_text="Model answer or key points"),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="List of keywords for grading"
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["exam", "order"],
                "indexes": [
                    models.Index(
                        fields=["exam", "order"], name="questions_exam_id_6a4fc8_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["course", "is_published"], name="exams_course__88a174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["start_time", "end_time"], name="exams_start_t_d9bb07_idx"
            ),
        ),
    ]
