# Generated by Django 4.2.27 on 2026-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['exam']},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='questions_exam_id_6a4fc8_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='questions_exam_id_519196_idx'),
        ),
    ]
